fix: Fixed code coverage not being run and not failing on failed test

diff --git a/tests/gen_coverage.sh.in b/tests/gen_coverage.sh.in
--- a/tests/gen_coverage.sh.in
+++ b/tests/gen_coverage.sh.in
@@ -5,6 +5,12 @@ cd @CMAKE_BINARY_DIR@/bin/test
 
 for test in `ls Survive-*-test*`; do
     ./$test
+    exit_code=$?
+
+    if [ $exit_code -ne 0 ]; then
+        echo "Test $test failed with exit code $exit_code"
+        exit $exit_code
+    fi
 done
 
 cd -
